pipeline {
    agent any
    environment {
        REGISTRY = "localhost:5000"
    }
    stages {
        stage('Verify') {
            steps {
                dir('GraphQL') {
                    sh 'chmod +x ./CI/scripts/00-verify.sh'
                    sh './CI/scripts/00-verify.sh'
                }
            }
        }
        stage('Build') {
            steps {
                dir('GraphQL') {
                    sh 'chmod +x ./CI/scripts/01-build.sh'
                    sh './CI/scripts/01-build.sh'
                }
            }
        }
        stage('Test') {
            steps {
                dir('GraphQL') {
                    sh 'chmod +x ./CI/scripts/02-test.sh'
                    sh './CI/scripts/02-test.sh'
                }
            }
        }
        stage('Push') {
            steps {
                dir('GraphQL') {
                    sh 'chmod +x ./CI/scripts/03-push.sh'
                    sh './CI/scripts/03-push.sh'
                }
            }
        }
    }
}
